name: Knip Unused Code Check

on:
  pull_request:
    branches:
      - '**'

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  knip:
    name: Check for unused code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run Knip
        run: yarn knip
